import { STALE_GHOST_OBJECT_ID } from './resolve-gas-payment';

const LOCALNET_MYDATA_KEY_SERVER_URL = 'http://127.0.0.1:2024';

function looksLikeStaleGasCoinError(message: string): boolean {
  return (
    message.includes(STALE_GHOST_OBJECT_ID) &&
    (message.includes('does not exist') ||
      message.includes('stale') ||
      message.includes('gas'))
  );
}

function looksLikeMyDataKeyServerTypeError(message: string): boolean {
  return (
    message.includes('dynamic_field::Field') ||
    (message.includes('does not exist') &&
      message.includes('KeyServer') &&
      !looksLikeStaleGasCoinError(message))
  );
}

export function formatCreateGroupError(err: unknown): string {
  if (!(err instanceof Error)) {
    return 'Failed to create group.';
  }

  const message = err.message;
  const isLocalnet = import.meta.env.VITE_MYSO_NETWORK === 'localnet';
  const looksLikeMyDataFetchFailure =
    message === 'Failed to fetch' ||
    message.includes('ERR_CONNECTION_REFUSED') ||
    message.includes(':2024');

  if (isLocalnet && looksLikeMyDataFetchFailure) {
    return (
      `MyData key server not reachable at ${LOCALNET_MYDATA_KEY_SERVER_URL}. ` +
      'Start localnet with `myso start --with-mydata` and confirm the key server ' +
      'logs show it listening on port 2024 (no "Duplicate key server object ID" error). ' +
      'Set VITE_MYDATA_KEY_SERVER_OBJECT_IDS to the parent KEY_SERVER_OBJECT_ID from that output ' +
      '(verify with `myso client object <id>` — type must be key_server::KeyServer, not dynamic_field::Field).'
    );
  }

  if (
    message.includes('InvalidKeyServerError') ||
    (message.includes('Key server') && message.includes('is not valid'))
  ) {
    return (
      'MyData key server failed cryptographic verification (on-chain public key vs HTTP /v1/service). ' +
      'Rebuild myso from myso-core (gen-seed + derive-key index 0 bootstrap), regenesis with --with-mydata, ' +
      'and confirm startup PUBLIC_KEY matches key-server log "Client local_key_server uses public key". ' +
      'Update VITE_MYDATA_KEY_SERVER_OBJECT_IDS and restart pnpm dev.'
    );
  }

  if (
    message.includes('DeprecatedSDKVersion') ||
    message.includes('SDK version is deprecated')
  ) {
    return (
      'MyData key server rejected the SDK version sent by @socialproof/mydata. ' +
      'Localnet key-server config should set ts_sdk_version_requirement to >=0.0.4 ' +
      '(generated by `myso start --with-mydata` after rebuilding myso). ' +
      'Run `myso start --force-regenesis --with-mydata`, update chat-app/.env, restart `pnpm dev`, ' +
      'and retry Create Group.'
    );
  }

  if (
    message.includes('No RPC-verified gas coins') ||
    message.includes('stale object(s)')
  ) {
    return message;
  }

  if (looksLikeStaleGasCoinError(message)) {
    return (
      'Transaction referenced a stale gas coin from listCoins (' +
      `${STALE_GHOST_OBJECT_ID}). ` +
      'Your signer may still be funded — run `myso client gas <your-address>` and compare with ' +
      '"[chat-app] signer gas" in the console. Restart dev server after updating the app; ' +
      'sign-and-wait now resolves gas via RPC-verified coins before sign.'
    );
  }

  if (looksLikeMyDataKeyServerTypeError(message)) {
    return (
      `${message} ` +
      'VITE_MYDATA_KEY_SERVER_OBJECT_IDS must be the parent key_server::KeyServer object ID ' +
      'from `myso start --with-mydata` (not the dynamic_field::Field child). ' +
      'Verify with `myso client object <id>` and check "[chat-app] mydata key servers" in the console.'
    );
  }

  if (message.includes('does not exist')) {
    return (
      `${message} ` +
      'Check "[chat-app] mydata key servers", "[chat-app] signer gas", and ' +
      '"[chat-app] create-group tx inputs" in the console. After `--force-regenesis`, update .env ' +
      'from the latest `myso start` output and restart `pnpm dev`.'
    );
  }

  if (message.includes('No valid gas coins')) {
    return (
      `${message} Fund your signer on localnet: ` +
      '`myso client faucet <your-address>` (see "[chat-app] signer gas" in the console).'
    );
  }

  return message;
}
